### PR TITLE
Dhruv assignment2

### PR DESCRIPTION
**Pull request by DhruvTh**

### CODE REVIEW

**Comment by chaitany10** [comment]
Name your file by your name.
Sudoku qn is not proper.
input 
2
3
0
0
3
Wrong way of checking sudoku..try using "not in" some list. Keep a count of every number.

**Comment by chaitany10** [comment]
I can still merge as it was bonus, reply

**Comment by DhruvTh** [comment]
[4q.txt](https://github.com/IE-NITK/ML-SMP-2019/files/3160520/4q.txt)

**Comment by DhruvTh** [comment]
I upload the 4th question in conversation. It's okay or should I do  pull
request again with new file?

**Comment by chaitany10** [comment]
First change the filename to ur name

**Comment by chaitany10** [comment]
And still sudoku qn is not proper

**Comment by DhruvTh** [comment]
I can't understand. Can you just tell me exact
Problem?

**Pull request merged**
