### PR TITLE
Assignment 1- Karn Tiwari

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by krahulreddy** [comment]
Please change the name of the text file, and add it to Assignment 1 folder and send PR.

**Comment by ghost** [comment]
I have done please check....

**Comment by krahulreddy** [comment]
Please refer to the current structure of the repo. Remove the 'Readme.txt' that you added. Do not rename existing files. Make sure file structure is like "Assignment 1/(Your Name)/(Your Name).txt" or "Assignment 1/(Your Name).txt"

**Comment by ghost** [comment]
Now it's fine or not...

**Comment by krahulreddy** [comment]
Excellent Work!!

**Pull request merged**
